#!/bin/sh

case "$1" in
start)
	if ! grep -qs ' /proc proc ' /proc/mounts; then
		mount -t proc none /proc
	fi
	if ! grep -qs ' /sys sysfs ' /proc/mounts; then
		mount -t sysfs none /sys
	fi
	mkdir -p /sys/kernel/debug
	if ! grep -qs ' /sys/kernel/debug debugfs ' /proc/mounts; then
		mount -t debugfs none /sys/kernel/debug
	fi
	;;
stop)
	if grep -qs ' /sys/kernel/debug debugfs ' /proc/mounts; then
		umount /sys/kernel/debug
	fi
	;;
esac
