default mainline

label mainline
    menu label Mainline OpenSBI + U-Boot + Linux
    linux /Image
    fdt /sun300i-v821-avaota-f1.dtb
    append earlycon=uart8250,mmio32,0x42500000,115200,192000000 console=ttyS0,115200 root=/dev/mmcblk0p2 rootwait highres=0 nohz=off
